# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Career Endorsement Tracker' do
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
  pod 'LBTAComponents'
  pod 'JGProgressHUD'
  pod 'FoldingCell'
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
end
