# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Career Endorsement Tracker' do
  use_frameworks!

# Pods for Endrsd


pod 'JGProgressHUD'
pod 'FoldingCell'
pod 'BreakOutToRefresh'

end
