# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Career Endorsement Tracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  #pod 'OneSignal', '>= 2.6.2', '< 3.0'
  #pod 'LBTAComponents'
  #pod 'JGProgressHUD'
  pod 'FoldingCell'
  pod 'MBRadioCheckboxButton'

end